### ISSUE TITLE
Is there a demo?

### ISSUE THREAD

**Issue by regular** [matthewmorrone/morse#1]

**Comment by matthewmorrone** [comment]
Yeah! It's at www.matthewmorrone.com/morse-code. It's been a little while so let me know if anything's broken (in chrome).

**Comment by matthewmorrone** [comment]
Sorry about that, guess my attempt at URL rewriting in the .htaccess was messing with that. It's up now!

**Comment by regular** [comment]
Nice, thanks! It's working perfectly.
